### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by enomto** [gmuraleekrishna/semantic-segmentation#1]
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    from helpers import get_images_and_masks, convert_to_labels, get_model_memory_usage
  File "/home/atsushi/keras/work/semantic-segmentation/helpers.py", line 68
    print('{0}\r'.format(s), end='') 
                                ^
SyntaxError: invalid syntax

thank you

**Comment by gmuraleekrishna** [comment]
@enomto Can you make sure you have the latest code. Thanks

**Comment by enomto** [comment]
Thank you for your reply
I am using the latest code.

**Comment by gmuraleekrishna** [comment]
Sorry, I'm unable to reproduce the said error at my end.
